# Generated by Django 6.1 on 2026-09-09 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text="Xona raqami yoki nomi, masalan: '101' yoki 'Ayvon oldi 1'", max_length=20, unique=True)),
                ('price_per_night', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
    ]
