# Generated by Django 6.1 on 2026-09-11 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=50)),
                ('guest_phone', models.CharField(max_length=15)),
                ('date', models.DateField(help_text='The day the room is booked for / check-in day.')),
                ('nights', models.PositiveSmallIntegerField(default=1, help_text='1 = same-day, no overnight stay. Bump up only if the guest is actually staying over.')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prepaid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('paid_in_full', models.BooleanField(default=False, help_text='Tick this once the remaining balance is collected at check-in/visit.')),
                ('is_cancelled', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings_created', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.room')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
