# Generated by Django 6.1 on 2026-09-11 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='nights',
        ),
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(help_text='The day the room is booked for.'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='myapp.room'),
        ),
    ]
